### ISSUE TITLE
Add Examples to Documentation

### ISSUE THREAD

**Issue by gyrospectre** [Athena-Home-Loans/keydra#13]
It would be quite helpful to have a list of examples (Keydra secret specs, AWS SM secrets) for various use cases, for people to use when getting started. For example, "Rotating a Qualys Password to use for Splunk Qualys Integration".

Suggest a new page in the doco for Examples.

**Comment by gyrospectre** [comment]
Could do with more, but a few added to start this off.

**Comment by jangroth** [comment]
+1

I've set up Keydra for GitHub as a trial run and had a hard time figuring out what secrets to store where. It's also not obvious to me at this stage what `custodians` are being used for 🤔 

Anyways, great work with this project & thanks for sharing it with the community!

I've started working on GitLab integration and hope to be able to submit a PR at some stage if there's in appetite for that.

**Comment by gyrospectre** [comment]
Nice, excited to hear you're giving it a try! Point taken on the `custodians` key, let me add to the doco on this one. In short though, it's just a tag we use internally to know which team "own" the secret. It's just a free text tag. :-)

**Comment by pablogrigo** [comment]
Configuration examples can be found in the documentation: https://athena-home-loans.github.io/keydra/examples/iamsplunk/
