### ISSUE TITLE
Add different git hosting providers for configuration

### ISSUE THREAD

**Issue by leo-dcfa** [Athena-Home-Loans/keydra#22]
At the moment, there is a hard dependency between Keydra and bitbucket for configuration. As a developer I would like to choose the git hosting provider of choice based my organisation needs.

# Proposal

- Add a new module to Keydra called configuration_providers
- Add a environment value for the configuration provider which has a value for configuration provider (i.e. github, gitlab, bitbucket)
- Keydra will fetch configuration based on secret provider
- If secret configuration is not yet supported, throw an exception

**Comment by gyrospectre** [comment]
Isn't that what the `KEYDRA_CFG_PROVIDER` env var does? 

https://github.com/Athena-Home-Loans/keydra/blob/3954905384aa471d337a5e996a63b7932b5cf595/docsrc/sample_template.yaml#L29

As long as the provider specified here implements the `load_config` function, it should fetch the secret specs from the specified repo from that git hoster.

I may be wrong - I might try to implement a github provider to test this out.

**Comment by leo-dcfa** [comment]
Ah I see, I wasn't aware it had been implemented already

**Comment by gyrospectre** [comment]
No worries! I've confirmed this is the case; should have a Github provider up in the next day or so, which will at least mean peeps can choose from two config providers out of the box.

Will close this issue.
