### ISSUE TITLE
Missing IAM permission for SecretManager

### ISSUE THREAD

**Issue by jangroth** [Athena-Home-Loans/keydra#28]
I ran into this issue when setting up keydra for github:

```
[
  {
    "status": "fail",
    "msg": "Failed to read keydra/github from Secrets Manager: An error occurred (AccessDeniedException) when calling the GetSecretValue operation: User: arn:aws:sts::123456789012:assumed-role/batch-keydra/keydra is not authorized to perform: secretsmanager:GetSecretValue on resource: keydra/github"
  }
]
```

Easy to fix by adding the missing permission. I'm happy to submit a PR at a later stage.

**Comment by vludax** [comment]
Hi @jangroth, if you're using the sample execution role, then you'd need to tag the `keydra/github` secret with `managedby: keydra`, as that role can only access tagged secrets 🙂

https://github.com/Athena-Home-Loans/keydra/blob/main/docsrc/KeydraExecRole.yaml#L54

**Comment by jangroth** [comment]
Ah thanks, I missed that.

**Comment by gyrospectre** [comment]
Have added a line or two to the quick start docs to call this out and try to avoid others hitting the same issue.
